### ISSUE TITLE
Can only process files in a single directory

### ISSUE THREAD

**Issue by windgazer** [prantlf/grunt-embed-fonts#4]
When feeding this task multiple stylesheets in separate directories, the `options.baseDir` gets set for the first file only, after which references to the fonts are broken (if not within the same baseDir):

```
{
    files: {
        'styles/fonts/font1/style.base64.css': ['styles/fonts/font1/style.css'],
        'styles/fonts/font2/style.base64.css': ['styles/fonts/font2/style.css'],
    }
}
```

Given that the font-files are in the directory with their respective `style.css`, the second `style.css` will break.

**Comment by prantlf** [comment]
Thanks for noticing this!  Fixed by a98b0be71a0442811c6c28cc52edf6fcc8608f90 in version 0.2.2.
