### ISSUE TITLE
Wrong file size in WOFF header

### ISSUE THREAD

**Issue by windgazer** [prantlf/grunt-embed-fonts#5]
When using grunt-embed-fonts as-is (at least on a windows platform) the resulting BASE64 cannot be decoded correctly. Chrome reports 'incorrect files-size in WOFF header'.

Currently open PR (#2) resolved this issue when I manually patched my local install.

**Comment by tenaciousRas** [comment]
+1

**Comment by prantlf** [comment]
Thanks for noticing this and contributing the fix!

Included in version 0.2.1.
